FROM golang:alpine

# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache ca-certificates git

# Set the current working directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

RUN go mod download

# Copy the source from the current directory to the working Directory inside the container

COPY . .
# Build the Go app
RUN CGO_ENABLED=0 go test -v ./...

